name: 'Starts a GitHub Self Hosted Runner '
description: 'Greet someone and record the time'
inputs:
  github_pat:
    description: 'GitHub Personal Access Token used in Runner Registration'
    required: true
  task_definition:
    description: 'The name of the task definition'
    required: true
    default: 'gh-runner'
  cluster:
    description: 'The name of the ECS cluster where the task should be placed'
    required: true
  wait:
    description: 'Whether the action should wait until the task is in state RUNNING before finishing'
    required: true
    default: 'true'
  capacity_provider:
    description: 'The name of the desired Capacity Provider (attached to this cluster)'
    required: true
    default: 'default'
  task_role_arn:
    description: 'ARN of the role used to instantiate the task'
    required: false
  execution_role_arn:
    description: 'ARN of the role used during task execution'
    required: false
  task_params_file:
    description: 'JSON file (path) with extra configurations'
    default: 'task-params.json'
    required: false
outputs:
  task_id:
    description: 'The ID of the task in execution'
runs:
  using: 'docker'
  image: 'passeidireto/gh-runner-task-action'