on:
  push:
    tags:
      - 'v*'
name: Github release
jobs:
  github_release:
    name: Create github release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
  docker_push:
    name: Push image to docker registry
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        run: docker build -t passeidireto/gh-runner-task-action .
      - name: Docker Tag
        run: |
          docker tag passeidireto/gh-runner-task-action passeidireto/gh-runner-task-action:latest
          docker tag passeidireto/gh-runner-task-action passeidireto/gh-runner-task-action:${GITHUB_REF/refs\/tags\/v/}
      - name: Docker Push
        run: docker push passeidireto/gh-runner-task-action
