# Check if the action is actually working (Temporary)

name: Run Action
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        github_pat: ${{ secrets.GITHUB_TOKEN }}
        task_definition: 'gh-runner'
        cluster: 'ops-jobs'
        task_params_file: 'task-params-example.json'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CDK_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_SECRET_KEY }}
        AWS_DEFAULT_REGION:  ${{secrets.AWS_DEFAULT_REGION}}


