# Check if the action is actually working (Temporary)

name: Run Action
on: [push, pull_request]
jobs:
  pre-job-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Test Trigger
      uses: ./
      with:
        github_pat: ${{ secrets.PD_BOT_GITHUB_ACCESS_TOKEN }}
        task_definition: 'gh-runner'
        cluster: 'gh-runner'
        task_params_file: 'task-params-example.json'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.CDK_ACCESS_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.CDK_SECRET_KEY }}
        AWS_DEFAULT_REGION:  ${{secrets.AWS_DEFAULT_REGION}}
  build:
    runs-on: self-hosted
    container:
      image: python:3.9-slim
    needs: pre-job-test
    steps:
    - uses: actions/checkout@v2
    - run: python --version
